---

main_username: josh

docker_compose_path: '/opt/docker/compose'
docker_appdata_path: '/home/{{ main_username }}/docker/appdata'

# -----
# grog.package
# -----
package_list:
  - name: cabextract
  - name: cheese
  - name: curl
  - name: git
  - name: gnome-tweaks
  - name: gramps
  - name: iperf
  - name: joystick
  - name: keepassxc
  - name: peazip
  - name: pwgen
  - name: rpi-imager
  - name: steam
  - name: syncthing
  - name: unrar
  - name: veracrypt
  - name: vim
  - name: winetricks
  - name: wireguard

snap_list:
  - name: audible-for-linux
  - name: brave
  - name: cups
  - name: curl
  - name: discord
  - name: everdo
  - name: ffmpeg
  - name: firefox
  - name: jdownloader2
  - name: joplin-desktop
  - name: kolourpaint
  - name: obsidian
    classic: true
  - name: organize-my-files
  - name: poddr
  - name: retroarch
  - name: slack
  - name: spotify
  - name: sublime-text
    classic: true
  - name: ufw 


flatpak_list:
  - name: io.github.streetpea.Chiaki4deck
